version: '3.8'

services:
  # MySQL データベースサービス
  mysql:
    image: mysql:8.0
    container_name: connect-hub-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: connecthub
      MYSQL_USER: connecthub_user
      MYSQL_PASSWORD: connecthub_password
      MYSQL_INNODB_LOG_FILE_SIZE: 4M  # ログファイルサイズを小さくする
      MYSQL_INNODB_LOG_BUFFER_SIZE: 2M  # バッファサイズも小さくする
      MYSQL_TMP_DIR: /tmp/mysql_tmp  # 一時ディレクトリを変更
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - /tmp/mysql_tmp:/tmp/mysql_tmp
    networks:
      - connect-hub-network
    command: >
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci 
      --default-authentication-plugin=mysql_native_password 
      --host-cache-size=0 
      --innodb-log-file-size=4M 
      --innodb-log-buffer-size=2M 
      --tmpdir=/tmp/mysql_tmp
      --explicit_defaults_for_timestamp=1
      --max_allowed_packet=16M
      --innodb-buffer-pool-size=64M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "connecthub_user", "--password=connecthub_password"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # バックエンドサービス
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: connect-hub-backend
    restart: on-failure
    environment:
      NODE_ENV: development
      PORT: 8000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: connecthub_user
      DB_PASSWORD: connecthub_password
      DB_NAME: connecthub
      JWT_SECRET: your_jwt_secret_key
      NPM_CONFIG_LOGLEVEL: verbose
    ports:
      - "8000:8000"
    volumes:
      - backend_logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - connect-hub-network
  
  # フロントエンドサービス
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: connect-hub-frontend
    restart: always
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:8000/api
    ports:
      - "3000:3000"
    volumes:
      - frontend_logs:/app/logs
    depends_on:
      - backend
    networks:
      - connect-hub-network

volumes:
  mysql_data:
    driver: local
  backend_logs:
    driver: local
  frontend_logs:
    driver: local

networks:
  connect-hub-network:
    driver: bridge
